### ISSUE TITLE
Cannot find SteemConnector

### ISSUE THREAD

**Issue by ghost** [charlesjlee/steemBot#1]
It appears that the heroku python3.6 site package for piston is incomplete or, more likely, I am doing something wrong.  I'm trying to run steembot (which I named epfsteembot01) following your directions.  It builds on heroku but when I run it, I get:

heroku run python bot.py -a epfsteembot01
Running python bot.py on epfsteembot01... up, run.8416 (Free)
Traceback (most recent call last):
  File "bot.py", line 9, in <module>
    from piston.steem import Steem
  File "/app/.heroku/python/lib/python3.6/site-packages/piston/steem.py", line 3, in <module>
    from steem.steem import SteemConnector as SteemConnectorSteem
ImportError: cannot import name 'SteemConnector'

I went to the piston github but could not find a reference to steemConnector in steem.py.  Can you offer any advice?

**Comment by charlesjlee** [comment]
The piston library [xeroc/piston](https://github.com/xeroc/piston) is now deprecated; the successor is [xeroc/piston-cli](https://github.com/xeroc/piston-cli)

**Comment by ghost** [comment]
Closing without updating the repo didn't actually address the issue?

**Comment by ghost** [comment]
pip3 install piston-cli

change import in bot.py to 
from steem import Steem
